language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - DEPS="pip numpy scipy nose"
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION $DEPS
install:
  - travis_retry pip install -r requirements.txt
script:
  - nosetests --logging-level=INFO